apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-registry-config
data:
  config: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
      #oss:
      #    accesskeyid: DELETED
      #    accesskeysecret: DETELED
      #    region: oss-cn-hangzhou
      #    internal: false
      #    bucket: bucket
      #    rootdirectory: /storage/
      filesystem:
        rootdirectory: /storage
      cache:
        layerinfo: inmemory
      maintenance:
        uploadpurging:
          enabled: false
      delete:
        enabled: true
    http:
      addr: :5000
      secret: placeholder
      debug:
        addr: localhost:5001
    auth:
      token:
        issuer: registry-token-issuer
        realm: https://harbor.local/service/token
        rootcertbundle: /etc/docker/registry/root.crt
        service: token-service
    notifications:
      endpoints:
        - name: harbor
          disabled: false
          url: http://ui/service/notifications
          timeout: 3000ms
          threshold: 5
          backoff: 1s

  cert: |
    -----BEGIN CERTIFICATE-----
    MIIFzTCCA7WgAwIBAgIJAMw6Tuuq7+m8MA0GCSqGSIb3DQEBCwUAMH0xCzAJBgNV
    BAYTAkNOMREwDwYDVQQIDAhaaGVKaWFuZzERMA8GA1UEBwwISGFuZ1pob3UxDzAN
    BgNVBAoMBkhhcmJvcjELMAkGA1UECwwCSVQxFTATBgNVBAMMDGhhcmJvci5sb2Nh
    bDETMBEGCSqGSIb3DQEJARYEbm9uZTAeFw0xNjExMDMwOTMzNDdaFw0xNjEyMDMw
    OTMzNDdaMH0xCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhaaGVKaWFuZzERMA8GA1UE
    BwwISGFuZ1pob3UxDzANBgNVBAoMBkhhcmJvcjELMAkGA1UECwwCSVQxFTATBgNV
    BAMMDGhhcmJvci5sb2NhbDETMBEGCSqGSIb3DQEJARYEbm9uZTCCAiIwDQYJKoZI
    hvcNAQEBBQADggIPADCCAgoCggIBAKj1oXK5Zf4A3DcJpQVfgNFWbXmyKelUP77K
    iPyJlJkgObk+DV0twwnazPlAVwC1ERSy0uK1yK74R0oWt9Xa8MdvKmWpk4JLYXfi
    4UJoKalLPrapCAK3kC61etTqk0GHkAov3Bb6YFYewDaxGOCNp74kFGY97wgojiih
    BgAyAY+6ZLqKNxsutVaDZYdX0GwFWaC7yzkUr5K/ibtEpJnhhubVCUXAqjNRTnPs
    0jLvSBjkWeFaNH23xRpCrLh0ACzF9z6w/jVOFTBNQ+fxSjTu79syzwdL8I373C0m
    7xzPPe4sxSdPXDbWlQjrqbgI4ABstaWcex3eMNZeJ9/XiKCCEhFo6vEDYG5MmnF5
    N6WpeL6sFQ1IyA+yod0YmwLVWg180Kur+ubwji7i8ekjOH7HDLP5IaRe4SK5OiMC
    7F1HVNCGs8Lhdv0ZB/DYd8/+5g/l2G/srva0Kf5KRKnVYySR8kUz6Qr22KMG/KH9
    nX2YOjXqyoBiQOQLiTYpnmcnpuIyK2FLscL5A0BaGdOIGPj6JkCcLQYyS87omvjN
    79Uaheo9h+6CkNX7pOz97eNebWndytvhvs255ecQ3i8KgSOH/bw8RLsr70wos9sG
    t4+tmjL8n/MtlhjAlAmrcvRncosXAAL9vCCmvq5T4+YTRKWSavmgzaSfLfXf/Vu8
    pw22RMaNAgMBAAGjUDBOMB0GA1UdDgQWBBQPmFoF5w0bq7RQYbBWB86yG8Y4PjAf
    BgNVHSMEGDAWgBQPmFoF5w0bq7RQYbBWB86yG8Y4PjAMBgNVHRMEBTADAQH/MA0G
    CSqGSIb3DQEBCwUAA4ICAQCPyumFEAmz89IY4ZmUiYqi+2Y8G1T8qP/lxPXeMTHq
    F9vBSKKaRU++JdsOmSZFhCx2dnWphAbb55MT9Esof9ZyL+mkupAjXUDSqpyh/mTM
    1ArNYADnpR0aNVP1w+gxcEamujSk21u8hdCVc803V73A6iNAB3Lr6uaIEm9YUXg2
    E7ZiQc4UFYhuDor9nX7uc9LEYttBckyGEBYWLpkMXIP/vss+lP8f5hjChcxWfqp9
    94sXgkNRlfArN9nGF5rGsY3W+SSlfDHR8MYj6gAY40mc+6dx8cqu7jhogk3eUelv
    GucLRJOERugaw8eGF0wLzLCW2dpbV5Oy3OsuM7cVrXfRE7IAyd+rFMrA7c4q97Gd
    OVFUmpmZr1HZZbJDZXw/+yuhh1D2pdMWDnoULang47KuYBO3pyNJRtPraSXnCpeA
    6r64vt1FmbCCwb/mi063Sb+gZc/KvqWJJ2hnhsZAuz3urv32Go/jXvkB8vzeU87z
    ZEp+/oSiJroI5iF4g7WVKxc/ONjf/DZP9nQkMpovHTDse1Sm4uT6VMK8JtG7Zclb
    m0vAUG/VAz6rRJrANkNd9yWYuzep7SVZfO6WT0Ls7LLeQPIlD/2NZbazn/bg+3u1
    Vk5SzfUW5xjqKDfCX3OJrUiphZjnRYKnmnjoCGPbduTnzGJMgcRFiVUyb5PmNvqs
    sA==
    -----END CERTIFICATE-----

