apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USR: root
  MYSQL_PWD: root123
  UI_SECRET: GA4x7dv73QjCsLOd
  SECRET_KEY: secretkey1234567
  CONFIG_PATH: /etc/jobservice/app.conf
  REGISTRY_URL: http://registry:5000
  VERIFY_REMOTE_CERT: "on"
  MAX_JOB_WORKERS: "3"
  LOG_LEVEL: debug
  LOG_DIR: /var/log/jobs
  GODEBUG: netdns=cgo
  EXT_ENDPOINT: https://harbor.local
  TOKEN_URL: http://ui
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
