apiVersion: v1
kind: ReplicationController
metadata:
  name: jobservice-rc
  labels:
    name: jobservice-rc
spec:
  replicas: 1
  selector:
    name: jobservice-apps
  template:
    metadata:
      labels:
        name: jobservice-apps
    spec:
      containers:
      - name: jobservice-app
        image: test.caicloud.io/harbor/jobservice:0.4.0
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USR
            value: root
          - name: MYSQL_PWD
            value: root123
          - name: UI_SECRET
            value: GA4x7dv73QjCsLOd
          - name: SECRET_KEY
            value: secretkey1234567
          - name: CONFIG_PATH
            value: /etc/jobservice/app.conf
          - name: REGISTRY_URL
            value: http://registry:5000
          - name: VERIFY_REMOTE_CERT
            value: "on"
          - name: MAX_JOB_WORKERS
            value: "3"
          - name: LOG_LEVEL
            value: debug
          - name: LOG_DIR
            value: /var/log/jobs
          - name: GODEBUG
            value: netdns=cgo
          - name: EXT_ENDPOINT
            value: https://localhost.caicloud.io
          - name: TOKEN_URL
            value: http://ui
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/jobservice
        - name: logs
          mountPath: /var/log/jobs
      volumes:
      - name: config
        configMap:
          name: harbor-jobservice-config
          items:
          - key: config
            path: app.conf
      - name: logs
        persistentVolumeClaim:
          claimName: log-pvc 
