apiVersion: v1
kind: PersistentVolume
metadata:
  name: db1
  labels:
    type: db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/db1
