apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-ui-config
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USR: root
  MYSQL_PWD: root123
  REGISTRY_URL: http://registry:5000
  CONFIG_PATH: /etc/ui/app.conf
  HARBOR_REG_URL: harbor.local
  HARBOR_ADMIN_PASSWORD: Harbor12345
  HARBOR_URL: http://ui
  AUTH_MODE: db_auth
  LDAP_URL: ldaps://ldap.mydomain.com
  LDAP_BASE_DN: uid=%s,ou=people,dc=mydomain,dc=com
  LOG_LEVEL: debu
  UI_SECRET: GA4x7dv73QjCsLOd
  SECRET_KEY: secretkey1234567
  GODEBUG: netdns=cgo
  EXT_ENDPOINT: https://harbor.local
  TOKEN_URL: http://ui
  SELF_REGISTRATION: "on"
  USE_COMPRESSED_JS: "on"
  VERIFY_REMOTE_CERT: "on"
  TOKEN_EXPIRATION: "30"
  config: |
    appname = registry
    runmode = dev
    [lang]
    types = en-US|zh-CN
    names = en-US|zh-CN
    [dev]
    httpport = 80
    [mail]
    host = smtp.mydomain.com
    port = 25
    username = sample_admin@mydomain.com
    password = abc
    from = admin <sample_admin@mydomain.com>
    ssl = false
  pkey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKAIBAAKCAgEAqPWhcrll/gDcNwmlBV+A0VZtebIp6VQ/vsqI/ImUmSA5uT4N
    XS3DCdrM+UBXALURFLLS4rXIrvhHSha31drwx28qZamTgkthd+LhQmgpqUs+tqkI
    AreQLrV61OqTQYeQCi/cFvpgVh7ANrEY4I2nviQUZj3vCCiOKKEGADIBj7pkuoo3
    Gy61VoNlh1fQbAVZoLvLORSvkr+Ju0SkmeGG5tUJRcCqM1FOc+zSMu9IGORZ4Vo0
    fbfFGkKsuHQALMX3PrD+NU4VME1D5/FKNO7v2zLPB0vwjfvcLSbvHM897izFJ09c
    NtaVCOupuAjgAGy1pZx7Hd4w1l4n39eIoIISEWjq8QNgbkyacXk3pal4vqwVDUjI
    D7Kh3RibAtVaDXzQq6v65vCOLuLx6SM4fscMs/khpF7hIrk6IwLsXUdU0IazwuF2
    /RkH8Nh3z/7mD+XYb+yu9rQp/kpEqdVjJJHyRTPpCvbYowb8of2dfZg6NerKgGJA
    5AuJNimeZyem4jIrYUuxwvkDQFoZ04gY+PomQJwtBjJLzuia+M3v1RqF6j2H7oKQ
    1fuk7P3t415tad3K2+G+zbnl5xDeLwqBI4f9vDxEuyvvTCiz2wa3j62aMvyf8y2W
    GMCUCaty9GdyixcAAv28IKa+rlPj5hNEpZJq+aDNpJ8t9d/9W7ynDbZExo0CAwEA
    AQKCAgBeBcLASve879GcNxvD76+JzuTBEipMk/udOqwcjJtK0yoMMcHSFoMw2rey
    BOHlnN1SfWjpjGuPIs7ZJedLdLkE4pHfXQyfNz+YLYNZJwn4Ec1mbI3upSPxOkCO
    d7NWhg/b+2Ioz1AI3LfuN4M2gt3T69QGSXTZP2hMp77lIO7JgtpHDF86GzYCXMCF
    HpL3acrErXyb2S0TJs+IjNxkXaJqlibA0ERmplpYHHOksI+Yeoqh40bOpxNiV7Qy
    OStXvxqlomz0UO1tobGmQxoedtC3VIDs+I93E68k2UO67oDyJ6vXAky4n5T0D+C0
    bwvocJZtALVqm5jl0iOyZwi6+Wb/rVdnKHP410PeDniJktl37wu+3n6xyJMqEc2Z
    GclFIJN3GyylU0EvEQracqnzvH5gOrgiqbAL1jdwzHfSFqt65rpjnoC+TeeUJnqw
    7m787yPJiYvw33vfbMqhXKEVP/05VZ2Rco2ZzaPnMZoyDtKs6AcvBC4ZnrZN+WH/
    oiGOYxtpbaZx7zcpoKYX3OUKypzkBEGnFXZJU+afCAXKCWcHy9E/KkcYuVr9isBa
    xL6ao9BkAAIlPlXddZNi0IAt8HEZVWeAjJlXqnRn3zsl8HGFPykyGfrmqm1q099X
    2rbbI2AUScqaGqERqhs2ZDBeRFHKA74XT23B/w9fe0JC2TUhQQKCAQEA3LobasJt
    wYT/2SzxHQFOf0gjugEomvxKdsKjO3s2J4fPLrRWC73stKUssKvwOxJZi04Z2MBT
    Lag9KyUxgSGc3hLronma7OdNLM1mvMagDgVrG+i/wHWQDPn+WEs8NoyJ1zMvXcjr
    ZFIbCV7UTm6DOAyEj13CRscZ7j2O3DWnhG/AehZDgwm5H1/DrD8GiPvGC3FrvSWs
    Q47HGL/3ZOV6q7aUjZjuOzRZGhOT6n3S63QkAjkz9omFZDnzA9usCsaA/sODN9I8
    GuEKnc7HWBpVZQHk9s3nvtMTx25gmtfuCwp52Xmf+LleIqvZIw7ogY9hU8THaHEA
    6dLPxSw6ddHhFQKCAQEAw/W6GEsbbucT+BNouoyPsFVfE3KuYVSbEBTOAfBBzjY7
    3YrZDfxzafAN/S5EvbBkG7Isxe4elSKwM2RKdbtaukQjp1pJmYULoORTbxN3Uy3q
    ihBWWNmgntkNO6Bv6NKCo5KVpBpJQKmREMpLgEL5iKODUWmOXjuACXS+twASXkKJ
    4r/1vcMbfvU/G18GOa+wl9pW1pj/EZjX/pOnhl05F7MlkSK7JZegsgPpPeBZAQCQ
    Bx/r//WMOvZcCRigA+JMI7zJPecmvgoq1k69N8+YSpGQ6IIFMi//62MaeW6sMW89
    2gswoplPRX/CB9/NkiC/lcw1YbfEOgjrcOsbnLZ9mQKCAQEAtZrF7gu0RBGKc4P/
    iW7GyABxrJtBbmr/VUEFDm5sew/JTdMALL8B3ws7fsyoZeHOHMiQiX6LsTgHw9Th
    Ky6dozWL++zzo9EW9TK2QcFmdMLOgnL4OYBAmfyh4MFd9D+jNZUedppV2f+X0Rjd
    sv5IJjheZJquuo8b7aFmRhY7EsLjaU+iElFQp9ih5LkiRlhodIfILiKt3hO+CcX/
    5VrNmDQre2kFMV77pHHRNJB7lk/DRLUN5Nz3DCSFpnn5zg/OmE4CS05FN5RKqNY1
    u25HLkjluo5lCuMeFerhvuTELP9ci6r/DKRvKDWd/LNKZzaxzDtOGcdIChnx6nde
    Tgv1lQKCAQA4UiPOX6fe1CN1JX7wPv39XEwbNtbPupVmpdQf0oHXVtcV8ZY44tn5
    FLmwjt/K9SuQmkEsEihQDMw/uQ99jv+gkXz92IFW0lppP7aLMjkVexjx3YgzuTjk
    7tVS0eXYMMjDYpoHtFZhc1ryTHIuxxEZKIXRnFkC1G8USK2XwzmERfODbFCg3bbF
    Yo9kuob7hXdn7aUPwKFu2VMbJCz9/UUvfpnJgQXw5AeXonAjDJwIIbVDlvUpd9V6
    DNye8Kjs9NmVW+krFYiZDisJtU/E/rFynSvc56G+rvULHky5oglzm9lXFehAk3ep
    LfMCeFyJJ0hpMWwWTc7kLzQcHDavb/PhAoIBACTR2BdZtHdigmoPs5hSiCZF5B3Q
    Xl0Wnrm8JMUunJLvFX9qmPiOAA3nQhcKewYB9QdfgKIXAYy0pWW6kRrjWQDf8QpU
    VlhrBNABZwH/7ppeg30yb/KC1mBsJbYiR9bzER9L+MQkfy/q9IIMoy8cwdOYPc/C
    MsL3IUn/Wx5SS8tRvaOUwLTSag3ODw9TT+v4AAQ5ao+R1FhVZfiR8fyDpRrcx1pK
    N6lqc++xJ3Ks6RUoWTCzrHI5kUzTwdH16SMLxPQDf2c3KuFaP8nlQPke63QizsoQ
    MmzvhAC/hN0JX1AX2vkFYHUVU5kYO2122VTzdn6XC0yUHj8MAWGJ9P070FY=
    -----END RSA PRIVATE KEY-----


